# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 68fccff215be3a0b867e0070417f7557c731cec459a206ebc4c76c634b2a08310cd7bc24a69ed084c090997cd7d96c40483ad1a9b9d8da88480aebeaf4d28295

test:
  secret_key_base: a326d484092a0041c1758b4fcaba02d58e784eb67cc0e33b035acf598ccea1f377fb80203bd9aed5fa0d8ac0a51effd7e1ba9a6c7bd5e90e2587c11860af3cc5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
